### ISSUE TITLE
Replace org.json with a friendly licensed JAR

### ISSUE THREAD

**Issue by davsclaus** [braintree/braintree_java#58]
In the 2.73.0 release there was this big commit that added org.json.json JAR dependency
https://github.com/braintree/braintree_java/commit/7497c1871b1dbaff3310cd65a58630feca143383

Its only used in one class, Http, where the `JSONObject` class is used. 

As org.json has a special license that is not business friendly its has been deemed x-category at Apache Software Foundation and cannot be used whatsoever.
https://www.apache.org/legal/resolved.html#json

I wonder if braintree-java can look into using another small JSon library, like simplejson, or even jackson etc.

If not then we would have to remove camel-braintree from Apache Camel going forward in the future. Or stop at version 2.72.0 which was the last version of braintree-java that does not use org.json
https://issues.apache.org/jira/browse/CAMEL-12180

**Comment by crookedneighbor** [comment]
Thanks for bringing this up, we'll look at this today.

**Comment by nofuss** [comment]
Is there any update on this issue? The Braintree component for Apache Camel is an important part of a project we are working on, and it would be unfortunate for it to be dropped because of the licensing issue.

I have created a provisional pull request that replaces the library with Jackson here: https://github.com/braintree/braintree_java/pull/60

As you can see, the change is minimal, but I would very much appreciate  help in verifying the work and whatever is needed to get the issue resolved.

**Comment by crookedneighbor** [comment]
The next release will use [Jackson JR](https://github.com/FasterXML/jackson-jr). Thanks for feedback on the licensing issue. Hoping to get a release out this week.

**Comment by crookedneighbor** [comment]
This should be fixed in v2.75.0 which was just released. Going to close this, but feel free to comment here if you need further assistance.

**Comment by oscerd** [comment]
release 2.75.0 doesn't seem to be in central.

**Comment by crookedneighbor** [comment]
You're right, I missed that step in the deploy process. Should be up in a few hours.

**Comment by oscerd** [comment]
Thanks :-)

**Comment by crookedneighbor** [comment]
It should be on central now. Thanks for mentioning it!

**Comment by oscerd** [comment]
:-)
