### ISSUE TITLE
PayPal - PaymentMethodNonce.find()

### ISSUE THREAD

**Issue by GaL3n** [braintree/braintree_java#72]
### General information

* SDK/Library version: 2.96
* Environment:  Sandbox and Production
* Language, language version, JAVA

### Issue description

PaymentMethodNonce.find() in PHP returns useful PayPal buyer information at Server Side level as the Payer ID or Shipping Address selected by the user on PayPal pages.

The Java SDK seems that doesn't have any method to access those data, that actually are transferred to the merchant server,

Can you please consider to add a specific method to allow merchants to treat this data before the payment is done ? 

Thanks,
Stefano

**Comment by quinnjn** [comment]
This method is available, here is the [reference documentation for find](https://developers.braintreepayments.com/reference/request/payment-method-nonce/find/java). 

All the server SDKs should have the same methods that return the same data. If you see any discrepancies let us know!

**Comment by GaL3n** [comment]
Hey guys,

there are discrepancies with data returned back. PHP returns more
information (see below) than Java.



Braintree\PaymentMethodNonce Object

(

    [_attributes:protected] => Array

        (

            [type] => PayPalAccount

            [nonce] => 3580b414-25ac-0656-5bca-e013a9ce4be3

            [description] => PayPal

            [consumed] =>

            [details] => Array

                (

                    [correlationId] => EC-7M3034294S918081A

                    [payerInfo] => Array

                        (

                            [email] => stefano098@buyer.it

                            [firstName] => Stefano

                            [lastName] => BuyerTre

                            *[payerId] => T6F4YU5NZ77J8*

                            [countryCode] => IT

                            [billingAddress] => Array

                                (

                                    [line1] => Via Unit� d'Italia, 5783296

                                    [line2] =>

                                    [city] => Napoli

                                    [state] => NAPOLI

                                    [postalCode] => 80127

                                    [countryCode] => IT

                                )



                            [shippingAddress] =>

                        )



                )



        )



)

**Comment by quinnjn** [comment]
Payer ID looks available in [2.89.0](https://github.com/braintree/braintree_java/blob/caf7a347cce74df2be2b4f713ba1f44117a0f022/CHANGELOG.md#2890).

**Comment by GaL3n** [comment]
Can you please check if you are able to retrieve the payerID using
PaymentMethodNonce.find() ?

Thanks

Il giorno lun 3 giu 2019 alle 19:50 Quinn J Neumiiller <
notifications@github.com> ha scritto:

**Comment by crookedneighbor** [comment]
In 2.89.0, we added the ability to pass the payer id in the transaction create call. We did not add an accessor to retrieve it from the payment method nonce class. ([nor is it documented in the response object](https://developers.braintreepayments.com/reference/response/payment-method-nonce/java))

The reason PHP has it is because there's a bit of magic in how the accessors are added, so it automatically gets new attributes as they are added to the API. Java though requires an explicit method to be added for the properties, and that does not exist for the all the properties on the details node: https://github.com/braintree/braintree_java/blob/caf7a347cce74df2be2b4f713ba1f44117a0f022/src/main/java/com/braintreegateway/PaymentMethodNonceDetails.java#L18-L29

Thanks for reporting it, it's on our radar.

In the meantime, you have the payment method token, so you can still look up the payer id using the payment method object: https://github.com/braintree/braintree_java/blob/caf7a347cce74df2be2b4f713ba1f44117a0f022/src/main/java/com/braintreegateway/PayPalAccount.java#L58-L60

**Comment by crookedneighbor** [comment]
This is fixed in 2.97.0 https://github.com/braintree/braintree_java/blob/master/CHANGELOG.md#2970
