### ISSUE TITLE
Can we use this SDK to trigger variable amount recurring payments ?

### ISSUE THREAD

**Issue by salah-ghanim** [braintree/braintree_java#74]
Our product is a pay per use product and nether us or the customer will know how much they will pay until the usage ends (like bike sharing, scooters ...).

Is there anyway to use braintree APIs to trigger a variable amount payment after creating a contract with the user ?

ideal scenario
User choose braintree / paypal as payment method and confirm that we can charge him.

2. user uses the product, price is calculated, invoice is sent and we charge via braintree api directly.

**Comment by crookedneighbor** [comment]
Both PayPal and Credit Card transactions do not require knowing the amount ahead of time.

Some payment methods (like Google/Apple pay) do require you to set the amount ahead of time, and do not allow variable recurring charges.

Please reach out to our support team for additional assistance. The issues on here are reserved for bugs in the sdk, rather than integration support. http://help.braintreepayments.com
